# Site
title:              Ow Zhiyin
bio:                'Someone once told me that humans should seek to solve problems, knowledge is just the tool which we use. That has been my mantra since. I constantly equip myself with more knowledge because
                    I aspire to use them and find solutions for the many problems out there.'
description:        "Web and iOS Developer with Finance Background | Entrepreneur"
reading_time:       true
words_per_minute:   200
myphoto:            'assets/img/ozyBlackwhite.jpg'
logo:               'assets/img/LightBulbOn.png'
background:         'assets/img/wdi2-project3.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                http://www.owzhiyin.com

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   owzhiyin

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            stubby_8
#facebook:           username
github:             ozy8
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           owzhiyin
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
